"use client";

/**
 * Web Audio synthesis for RPS match sounds. Zero asset bytes shipped — every
 * sound is generated by an OscillatorNode + a gain envelope at call time.
 *
 * Browsers block AudioContext creation until a user gesture, so we lazy-create
 * on first call. All public functions no-op safely on the server and when muted.
 */

const MUTE_KEY = "rps-muted";

let ctx: AudioContext | null = null;

function getCtx(): AudioContext | null {
  if (typeof window === "undefined") return null;
  if (ctx) return ctx;
  const Ctor: typeof AudioContext | undefined =
    window.AudioContext ?? (window as unknown as { webkitAudioContext?: typeof AudioContext }).webkitAudioContext;
  if (!Ctor) return null;
  try {
    ctx = new Ctor();
  } catch {
    return null;
  }
  return ctx;
}

export function isMuted(): boolean {
  if (typeof window === "undefined") return true;
  return window.localStorage.getItem(MUTE_KEY) === "1";
}

export function setMuted(muted: boolean): void {
  if (typeof window === "undefined") return;
  window.localStorage.setItem(MUTE_KEY, muted ? "1" : "0");
  window.dispatchEvent(new CustomEvent("rps-mute-change", { detail: muted }));
}

/**
 * Play a single tone with an exponential decay envelope.
 * `peak` is the gain at attack; the envelope decays toward silence over `durationMs`.
 */
function playTone(
  freq: number,
  durationMs: number,
  type: OscillatorType,
  peak = 0.18,
  startOffsetMs = 0
): void {
  const audio = getCtx();
  if (!audio) return;
  // Browser autoplay policy: the context can be created without a gesture but
  // starts suspended. Resume is a no-op once running and gets unblocked the
  // first time the user clicks anything — including the picker buttons.
  if (audio.state === "suspended") void audio.resume();
  const now = audio.currentTime + startOffsetMs / 1000;
  const osc = audio.createOscillator();
  const gain = audio.createGain();
  osc.type = type;
  osc.frequency.value = freq;
  gain.gain.setValueAtTime(0, now);
  gain.gain.linearRampToValueAtTime(peak, now + 0.005);
  gain.gain.exponentialRampToValueAtTime(0.0001, now + durationMs / 1000);
  osc.connect(gain).connect(audio.destination);
  osc.start(now);
  osc.stop(now + durationMs / 1000 + 0.02);
}

/** Countdown tick — short, bright, pitch-bumps on the last second. */
export function tick(opts?: { final?: boolean }): void {
  if (isMuted()) return;
  playTone(opts?.final ? 1320 : 880, 60, "square", 0.12);
}

/** Player pressed a choice button. */
export function click(): void {
  if (isMuted()) return;
  playTone(220, 70, "triangle", 0.2);
  playTone(440, 50, "triangle", 0.1, 20);
}

/** Round resolved — short ascending arpeggio (C5 E5 G5). */
export function reveal(): void {
  if (isMuted()) return;
  playTone(523.25, 120, "sine", 0.18, 0);   // C5
  playTone(659.25, 120, "sine", 0.18, 60);  // E5
  playTone(783.99, 200, "sine", 0.22, 120); // G5
}

/** Match finished in the top 3 — same arpeggio one octave up + a long high tone. */
export function flourish(): void {
  if (isMuted()) return;
  playTone(1046.5, 140, "sine", 0.18, 0);
  playTone(1318.5, 140, "sine", 0.18, 70);
  playTone(1568.0, 280, "sine", 0.22, 140);
  playTone(2093.0, 500, "triangle", 0.12, 380);
}
